subprojects {
    apply plugin: "java"

    group = 'eu.decentsoftware.holograms'

    repositories {
        mavenCentral()
        maven { url = "https://repo.codemc.io/repository/nms/" }
    }

    dependencies {
        if (!project.path.endsWith(":shared")) {
            implementation project(":shared")
        }
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(8)
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }
}