// Fabric needs this
pluginManagement {
    includeBuild('build-logic')
    repositories {
        mavenCentral()
        maven { url = 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven { url = 'https://repo.codemc.io/repository/nms/' }
        maven { url = 'https://repo.codemc.io/repository/maven-public/' }
        maven {
            url = 'https://libraries.minecraft.net/'
            content {
                includeGroupByRegex 'com\\.mojang.*'
            }
        }
        maven {
            url = 'https://repo.extendedclip.com/content/repositories/placeholderapi/'
            content {
                includeGroup 'me.clip'
            }
        }
    }
}

rootProject.name = 'DecentHolograms'

include ':shared'
include ':platform-api'
include ':plugin'
include ':nms'
include ':nms:nms-common'
include ':nms:nms-v1_8_R1'
include ':nms:nms-v1_8_R2'
include ':nms:nms-v1_8_R3'
include ':nms:nms-v1_9_R1'
include ':nms:nms-v1_9_R2'
include ':nms:nms-v1_10_R1'
include ':nms:nms-v1_11_R1'
include ':nms:nms-v1_12_R1'
include ':nms:nms-v1_13_R1'
include ':nms:nms-v1_13_R2'
include ':nms:nms-v1_14_R1'
include ':nms:nms-v1_15_R1'
include ':nms:nms-v1_16_R1'
include ':nms:nms-v1_16_R2'
include ':nms:nms-v1_16_R3'
include ':nms:nms-v1_17_R1'
include ':nms:nms-v1_18_R1'
include ':nms:nms-v1_18_R2'
include ':nms:nms-v1_19_R1'
include ':nms:nms-v1_19_R2'
include ':nms:nms-v1_19_R3'
include ':nms:nms-v1_20_R1'
include ':nms:nms-v1_20_R2'
include ':nms:nms-v1_20_R3'
include ':nms:nms-v1_20_R4'
include ':nms:nms-v1_21_R1'
include ':nms:nms-v1_21_R2'
include ':nms:nms-v1_21_R3'
include ':nms:nms-v1_21_R4'
include ':nms:nms-v1_21_R5'
include ':nms:nms-v1_21_R6'
include ':nms:nms-paper_v1_21_R6'
include ':nms:nms-v1_21_R7'
include ':nms:nms-paper_v1_21_R7'
include ':nms:nms-v26_1'
include ':nms:nms-v26_2'
