plugins {
    id 'dh.java-conventions'
}

dependencies {
    childProjects.values().collect { child ->
        implementation files("$rootDir/nms/${child.name}/build/libs/${child.name}.jar")
    }
}

compileJava {
    dependsOn childProjects.values().collect { child ->
        "${child.path}:jar"
    }
}

sourceSets {
    main {
        java {
            setSrcDirs([])
        }
        resources {
            setSrcDirs([])
        }
    }
    test {
        java {
            setSrcDirs([])
        }
        resources {
            setSrcDirs([])
        }
    }
}
