name: CI

on:
  push:
    branches: [ "main" ]
  pull_request: { }

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v6.0.0
        with:
          distribution: 'temurin'
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-home-cache-includes: |
            caches
            notifications
            jdks

      - name: Build and Run Unit Tests
        run: ./gradlew build

      - name: Verify Publishing
        run: ./gradlew publishToMavenLocal

      - name: Upload Plugin Jar
        uses: actions/upload-artifact@v7
        with:
          name: DecentHolograms
          path: plugin/build/libs/DecentHolograms-*.jar
          if-no-files-found: error
